version: '3'
services:
  setup:
    build:
      context: ./Dockerfiles
      dockerfile: setup
  logstash:
    build:
      context: ./Dockerfiles
      dockerfile: logstash
    volumes:
      - ./data/logstash:/usr/share/logstash/data
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - CLOUDTRAIL_BUCKET=${CLOUDTRAIL_BUCKET}
      - XPACK_MONITORING_ENABLED=false
      - PIPELINE_WORKERS=2
      - PIPELINE_UNSAFE_SHUTDOWN=true
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.0
    ports:
      - 5601:5601
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - cluster.name=cloudtrail-elk
      - bootstrap.memory_lock=true
      - http.host=0.0.0.0
      - "ES_JAVA_OPTS=-Des.enforce.bootstrap.checks=true"
