version: '3'
services:
  setup:
    build:
      context: ./Dockerfiles
      dockerfile: setup
  logstash:
    build:
      context: ./Dockerfiles
      dockerfile: logstash
    volumes:
      - ./data/logstash:/usr/share/logstash/data
    environment:
      - XPACK_MONITORING_ENABLED=false
      - PIPELINE_WORKERS=4
      - PIPELINE_UNSAFE_SHUTDOWN=true
      - PIPELINE_BATCH_DELAY=10
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - CLOUDTRAIL_BUCKET=${CLOUDTRAIL_BUCKET}
      - ACCESSLOG_BUCKET=${ACCESSLOG_BUCKET}
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.0
    ports:
      - 5601:5601
    environment:
      - elasticsearch.hosts=es01,es02,es03
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es02:/usr/share/elasticsearch/data
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es03:/usr/share/elasticsearch/data
